# Vulnerability Report for getwilds/python-dl:latest

Report generated on Fri Mar 28 01:52:38 UTC 2025

    ...Pulling
    âœ— Pull failed
[31mERROR  [0m Status: failed to get image getwilds/python-dl:latest: failed to pull image getwilds/python-dl:latest: GET https://index.docker.io/v2/getwilds/python-dl/manifests/latest: TOOMANYREQUESTS: You have reached your pull rate limit as 'tfirmanfh': dckr_jti_SotjxkFIYgrcinvz849xbHuPi4g=. You may increase the limit by upgrading. https://www.docker.com/increase-rate-limit, Code: 1 
Error generating all vulnerabilities report. Please try again later.
