# Vulnerability Report for getwilds/python-dl:1.0

Report generated on Fri Mar 28 01:52:38 UTC 2025

    ...Pulling
    âœ— Pull failed
[31mERROR  [0m Status: failed to get image getwilds/python-dl:1.0: failed to pull image getwilds/python-dl:1.0: GET https://index.docker.io/v2/getwilds/python-dl/manifests/1.0: TOOMANYREQUESTS: You have reached your pull rate limit as 'tfirmanfh': dckr_jti_eSEauuE9qS9ZogoDVulV2A2QiP8=. You may increase the limit by upgrading. https://www.docker.com/increase-rate-limit, Code: 1 
Error generating all vulnerabilities report. Please try again later.
